export const ICON_LINKS = [
  'content/icon/category/ic_category_foodndrink.png',
  'content/icon/category/ic_category_transport.png',
  'content/icon/category/icon_136.png',
  'content/icon/category/icon_124.png',
  'content/icon/category/icon_134.png',
  'content/icon/category/icon_125.png',
  'content/icon/category/icon_139.png',
  'content/icon/category/icon_84.png',
  'content/icon/category/icon_126.png',
  'content/icon/category/icon_138.png',
  'content/icon/category/icon_29.png',
  'content/icon/category/icon_130.png',
  'content/icon/category/ic_category_doctor.png',
  'content/icon/category/icon_137.png',
  'content/icon/category/ic_category_education.png',
  'content/icon/category/icon_107.png',
  'content/icon/category/icon_41.png',
  'content/icon/category/icon_53.png',
  'content/icon/category/icon_8.png',
  'content/icon/category/ic_category_other_expense.png',
  'content/icon/category/icon_70.png',
  'content/icon/category/icon_63.png',
  'content/icon/category/ic_category_donations.png',
  'content/icon/category/icon_94.png',
  'content/icon/category/icon_49.png',
  'content/icon/category/ic_category_invest.png',
  'content/icon/category/icon_140.png',
  'content/icon/category/ic_category_debt.png',
  'content/icon/category/ic_category_loan.png',
  'content/icon/category/icon_141.png',
  'content/icon/category/icon_4.png',
  'content/icon/category/icon_118.png',
  'content/icon/category/ic_category_salary.png',
  'content/icon/category/ic_category_other_income.png',
  'content/icon/category/icon_142.png',
  'content/icon/category/icon_143.png',
  'content/icon/category/icon_133.png',
  'content/icon/category/icon_15.png',
  'content/icon/category/icon_135.png',
  'content/icon/category/icon_127.png',
  'content/icon/category/icon_128.png',
  'content/icon/category/icon_129.png',
  'content/icon/category/ic_category_shopping.png',
  'content/icon/category/icon_17.png',
  'content/icon/category/icon_131.png',
  'content/icon/category/icon_9.png',
  'content/icon/category/ic_category_friendnlover.png',
  'content/icon/category/ic_category_entertainment.png',
  'content/icon/category/icon_6.png',
  'content/icon/category/icon_33.png',
  'content/icon/category/ic_category_travel.png',
  'content/icon/category/ic_category_medical.png',
  'content/icon/category/ic_category_pharmacy.png',
  'content/icon/category/icon_132.png',
  'content/icon/category/icon_10.png',
  'content/icon/category/icon_11.png',
  'content/icon/category/ic_category_give.png',
  'content/icon/category/ic_category_family.png',
  'content/icon/category/icon_38.png',
  'content/icon/category/icon_54.png',
  'content/icon/category/icon_35.png',
  'content/icon/category/icon_59.png',
  'content/icon/category/icon_withdrawal.png',
  'content/icon/category/ic_category_award.png',
  'content/icon/category/ic_category_interestmoney.png',
  'content/icon/category/ic_category_selling.png',
];
export const ICON_LINKS_ARRAY = [
  { link: 'content/icon/category/ic_category_foodndrink.png' },
  { link: 'content/icon/category/ic_category_transport.png' },
  { link: 'content/icon/category/icon_136.png' },
  { link: 'content/icon/category/icon_124.png' },
  { link: 'content/icon/category/icon_134.png' },
  { link: 'content/icon/category/icon_125.png' },
  { link: 'content/icon/category/icon_139.png' },
  { link: 'content/icon/category/icon_84.png' },
  { link: 'content/icon/category/icon_126.png' },
  { link: 'content/icon/category/icon_138.png' },
  { link: 'content/icon/category/icon_29.png' },
  { link: 'content/icon/category/icon_130.png' },
  { link: 'content/icon/category/ic_category_doctor.png' },
  { link: 'content/icon/category/icon_137.png' },
  { link: 'content/icon/category/ic_category_education.png' },
  { link: 'content/icon/category/icon_107.png' },
  { link: 'content/icon/category/icon_41.png' },
  { link: 'content/icon/category/icon_53.png' },
  { link: 'content/icon/category/icon_8.png' },
  { link: 'content/icon/category/ic_category_other_expense.png' },
  { link: 'content/icon/category/icon_70.png' },
  { link: 'content/icon/category/icon_63.png' },
  { link: 'content/icon/category/ic_category_donations.png' },
  { link: 'content/icon/category/icon_94.png' },
  { link: 'content/icon/category/icon_49.png' },
  { link: 'content/icon/category/ic_category_invest.png' },
  { link: 'content/icon/category/icon_140.png' },
  { link: 'content/icon/category/ic_category_debt.png' },
  { link: 'content/icon/category/ic_category_loan.png' },
  { link: 'content/icon/category/icon_141.png' },
  { link: 'content/icon/category/icon_4.png' },
  { link: 'content/icon/category/icon_118.png' },
  { link: 'content/icon/category/ic_category_salary.png' },
  { link: 'content/icon/category/ic_category_other_income.png' },
  { link: 'content/icon/category/icon_142.png' },
  { link: 'content/icon/category/icon_143.png' },
  { link: 'content/icon/category/icon_133.png' },
  { link: 'content/icon/category/icon_15.png' },
  { link: 'content/icon/category/icon_135.png' },
  { link: 'content/icon/category/icon_127.png' },
  { link: 'content/icon/category/icon_128.png' },
  { link: 'content/icon/category/icon_129.png' },
  { link: 'content/icon/category/ic_category_shopping.png' },
  { link: 'content/icon/category/icon_17.png' },
  { link: 'content/icon/category/icon_131.png' },
  { link: 'content/icon/category/icon_9.png' },
  { link: 'content/icon/category/ic_category_friendnlover.png' },
  { link: 'content/icon/category/ic_category_entertainment.png' },
  { link: 'content/icon/category/icon_6.png' },
  { link: 'content/icon/category/icon_33.png' },
  { link: 'content/icon/category/ic_category_travel.png' },
  { link: 'content/icon/category/ic_category_medical.png' },
  { link: 'content/icon/category/ic_category_pharmacy.png' },
  { link: 'content/icon/category/icon_132.png' },
  { link: 'content/icon/category/icon_10.png' },
  { link: 'content/icon/category/icon_11.png' },
  { link: 'content/icon/category/ic_category_give.png' },
  { link: 'content/icon/category/ic_category_family.png' },
  { link: 'content/icon/category/icon_38.png' },
  { link: 'content/icon/category/icon_54.png' },
  { link: 'content/icon/category/icon_35.png' },
  { link: 'content/icon/category/icon_59.png' },
  { link: 'content/icon/category/icon_withdrawal.png' },
  { link: 'content/icon/category/ic_category_award.png' },
  { link: 'content/icon/category/ic_category_interestmoney.png' },
  { link: 'content/icon/category/ic_category_selling.png' },
];
